# Generated by Django 5.1.1 on 2024-09-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0002_studentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
