# Generated by Django 5.1.1 on 2024-09-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0004_alter_studentmodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='file',
            new_name='document',
        ),
    ]
