# Generated by Django 5.1.1 on 2024-09-13 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0006_reporter_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='product_qty',
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(default='Hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='Defaulting', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectStudentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecart.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecart.studentname')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ManyToManyField(through='ecart.ProjectStudentRelationship', to='ecart.studentname'),
        ),
    ]
